<?php
/**
 * Typography settings
 *
 * @package Gautama
 */
return array(
	'title'            => esc_html__( 'Typography', 'gautama' ),
	'id'               => 'typography_settings',
	'customizer_width' => '400px',
	'icon'             => 'el el-fontsize',
	'fields'           => array(

		array(
			'id'          => 'body_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Body and Small Text Color', 'gautama' ),
			'subtitle'    => esc_html__( 'Set color for body and small text', 'gautama' ),
		),
		array(
			'id'          => 'headings_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Headings Text Color', 'gautama' ),
			'subtitle'    => esc_html__( 'Set color for the headings', 'gautama' ),
		),

		array(
			'id'             => 'custom_heading_title_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Custom Heading Title Font', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for heading title.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'custom_heading_subtitle_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Custom Heading Subtitle Font', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for heading subtitle.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'body_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Body Font', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for body tag.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h1_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H1 Headers Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for h1 tag.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h2_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H2 Headers Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for h2 tag.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h3_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H3 Headers Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for h3 tag.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h4_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H4 Headers Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for h4 tag..', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h5_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H5 Headers Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for h5 tag.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'h6_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'H6 Headers Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for h6 tag.', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'nav_1_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Navigation Level 1 Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for level 1 navigation', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'nav_2_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Navigation Level 2 Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for level 2 navigation (Sub Menus)', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),
		array(
			'id'             => 'nav_top_typography',
			'type'           => 'typography',
			'title'          => esc_html__( 'Header top navigation Typography', 'gautama' ),
			'subtitle'       => esc_html__( 'Specify typography for header top navigation', 'gautama' ),
			'description'       => esc_html__( 'Note: Line Height is calculated as follows (Font Size * Line Height) Example: Line height to be 1.8 and font size 16px (1.8 * 16) = 28.8. This will be your line height', 'gautama' ),
			'google'         => true,
			'font-backup'    => true,
			'all_styles'     => false,
			'letter-spacing' => true,
			'text-align'     => false,
			'units'          => 'px',
			'color'          => false,
		),

	),
);
